/* Generated By:JavaCC: Do not edit this line. OwlLangConstants.java */

/*
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version. You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

package org.UoR.OwlLang;

public interface OwlLangConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ONTQUE = 8;
  int ONTSTORE = 9;
  int ONTUR = 10;
  int ONTISR = 11;
  int ONTGRAMMA = 12;
  int ONTREGEX = 13;
  int ONTIND = 14;
  int ONTCLS = 15;
  int ONTPRO = 16;
  int CLS = 17;
  int PROPERTY = 18;
  int IND = 19;
  int REST = 20;
  int THAT = 21;
  int COLON = 22;
  int LPAREN = 23;
  int RPAREN = 24;
  int ASSIGN = 25;
  int EQ = 26;
  int NQ = 27;
  int PLUSEQ = 28;
  int SC_OR = 29;
  int SC_AND = 30;
  int SC_XOR = 31;
  int GETIND = 32;
  int REFNUMBER = 33;
  int STRING = 34;
  int URI = 35;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"$OWLLANG\"",
    "\"ONTSTORE\"",
    "\"ONTUNIQUEID\"",
    "\"ONTISRESOURCE\"",
    "\"ONTGRAMMA\"",
    "\"ONTREGEX\"",
    "\"ONTIND\"",
    "\"ONTCLS\"",
    "\"ONTPRO\"",
    "\"cls\"",
    "\"prop\"",
    "\"ind\"",
    "\"rest\"",
    "\"THAT\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"+=\"",
    "\"OR\"",
    "\"AND\"",
    "\"XOR\"",
    "\">>\"",
    "<REFNUMBER>",
    "<STRING>",
    "<URI>",
    "\"@\"",
    "\"^^\"",
  };

}
