/* Generated By:JavaCC: Do not edit this line. OntoLangConstants.java */

/*
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version. You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

package org.UoR.ontolang;

public interface OntoLangConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ONTQUE = 8;
  int ONTINS = 9;
  int ONTCLS = 10;
  int ONTSLT = 11;
  int CLS = 12;
  int SLOT = 13;
  int INS = 14;
  int FCT = 15;
  int FCTTYPEINS = 16;
  int FCTTYPENOTINS = 17;
  int THAT = 18;
  int COLON = 19;
  int LPAREN = 20;
  int RPAREN = 21;
  int SEMICOLON = 22;
  int ASSIGN = 23;
  int EQ = 24;
  int NE = 25;
  int PLUSEQ = 26;
  int SC_OR = 27;
  int SC_AND = 28;
  int SC_XOR = 29;
  int GETINS = 30;
  int REFNUMBER = 31;
  int STRING = 32;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"$ONTQUE\"",
    "\"ONTINS\"",
    "\"ONTCLS\"",
    "\"ONTSLT\"",
    "\"cls\"",
    "\"slot\"",
    "\"ins\"",
    "\"fct\"",
    "\"INSTANCE\"",
    "\"NOT_INSTANCE\"",
    "\"THAT\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"+=\"",
    "\"OR\"",
    "\"AND\"",
    "\"XOR\"",
    "\">>\"",
    "<REFNUMBER>",
    "<STRING>",
  };

}
